import Head from "next/head";
import {useSession} from "next-auth/react";
import Router from "next/router.js";
import { NextResponse } from "next/server.js";
import LoginTempComponent from "../components/LoginTempComponent.jsx";
import Dashboard from "../components/Dashboard.jsx";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";

// this is Landing page, here people will learn about the event and signup/login

export default function Home() {
  const {data:session} = useSession();
  
  useEffect(()=>{if (session!==null){
    Router.push('/dashboard') // redirects to Dashboard if user session is logged in session!
  }}, [session])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Futurepreneurs</h1>

      {/* <LoginTempComponent />
      <Dashboard/> */}
    </div>
  );
}
