import Head from "next/head";
import { useSession } from "next-auth/react";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useRouter } from "next/router.js";
import PendingUserRequests from "../components/PendingUserRequests.jsx";
import NavigationBar from "../components/NavigationBar";
import { toast, ToastContainer } from "react-toastify";
import Loading from "../components/Loading";



export default function PendingUserRequestsPage() {

  const { status } = useSession();
  const router = useRouter();

  // redirects to home if user not logged in 
  useEffect(() => {
    if (router.isReady) {
      if (status !== "loading" && status === "unauthenticated") {
        toast.error("Please Login First!")
        router.push("/")
      }
    }
  }, [status, router])

  return (
    <>
      <ToastContainer />
      {status === "loading" ? <Loading /> : status === "authenticated" &&
        <div className={styles.container}>
          <Head>
            <NavigationBar/>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          {/* <NavigationBar /> */}
          <br />
          <PendingUserRequests />
        </div>}
    </>

  );
}
