import Head from "next/head";
import {useSession} from "next-auth/react";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useRouter } from "next/router.js";
import Avatar, { ConfigProvider } from 'react-avatar';
import SearchTeamsWithSearch from "../components/SearchTeamsWithSearch.jsx";


// import NavigationBar from "../components/NavigationBar";

export default function Home() {
  const {data:session, status} = useSession();
  const router = useRouter();

  // redirects to home if user not logged in 
  useEffect(()=>{
    if (router.isReady){
      if (status === "unauthenticated" && status!=="loading"){
          router.push("/")
      }
    }
  }, [status, router])

  return (
    <ConfigProvider colors={['#130AE6','#236DCE','#BC304B','#BF3EC3','#E69951']}>
    <div className={styles.container}>
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <NavigationBar/> */}
      <br/>
      <SearchTeamsWithSearch />
    </div>
    </ConfigProvider>
  );
}
