import Head from "next/head";
import {useSession} from "next-auth/react";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useRouter } from "next/router.js";
import SearchTeamsWithSearch from "../components/SearchTeamsWithSearch.jsx";
import NavigationBar from "../components/NavigationBar";

export default function Home() {
  const {data:session} = useSession();
  const router = useRouter();
  
  useEffect(()=>{
    if (!router.isReady) return;

    if (session===null){
      router.push('/')
    }
  }, [router.isReady, session,router])

  return (
    <div className={styles.container}>
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar/>
      <br/>
      <SearchTeamsWithSearch/>
    </div>
  );
}
